name: Colorado History Photos Bot
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 14,2 * * *" # In UTC, every 7am and 7pm MTN

jobs:
  run-bot:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.8.1]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present

      - name: Run posting script
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: npm run start

      - name: Log scheduled posts count
        run: |
          COUNT=$(sqlite3 nodes.db "SELECT COUNT(*) FROM scheduled_nodes;")
          echo "Rows in scheduled_nodes table: $COUNT"
          echo "Pull the updates before adding more."
        continue-on-error: true

      - name: Commit and push updated nodes.db
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add nodes.db
          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add new ID from bot run"
            git push
          fi
