name: Scheduled Bot Job
on:
  schedule:
    - cron: "0 7,19 * * *" # Every 7am and 7pm, so 2 photos per day

jobs:
  run-bot:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.8.1]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present

      - name: Run bot script
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: npm run start

      - name: Commit and push updated nodes.db
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add nodes.db
          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add new ID from bot run"
            git push
          fi
